export const SKILLS = {
  core: [
    'TypeScript',
    'JavaScript (ES6+)',
    'React',
    'Next.js',
    'App Router',
    'Server Components',
    'SSR',
    'SSG',
    'HTML5',
    'CSS3',
    'Tailwind CSS',
  ],
  stateData: [
    'TanStack Query',
    'Zustand',
    'Redux Toolkit',
    'React Hook Form',
    'Zod',
    'Axios',
    'REST API',
  ],
  ui: [
    'Radix UI',
    'shadcn/ui',
    'Framer Motion',
    'Recharts',
    'i18n / l10n',
    'next-intl',
    'RTL',
    'Accessibility',
    'SEO',
    'Figma',
  ],
  quality: [
    'Vitest',
    'Jest',
    'Playwright',
    'Unit Testing',
    'Code Review',
    'CI/CD',
    'GitLab CI',
    'Docker',
  ],
  tools: [
    'Git',
    'GitHub',
    'GitLab',
    'Nx Monorepo',
    'pnpm',
    'Vite',
    'Biome',
    'ESLint',
    'Prettier',
    'Husky',
  ],
  backend: ['NestJS', 'Node.js', 'PostgreSQL', 'TypeORM', 'JWT'],
};

export type SkillKey = keyof typeof SKILLS;
export const SKILLS_KEYS = Object.keys(SKILLS) as SkillKey[];
